-- Create schema
CREATE SCHEMA BROKERS DEFAULT CHARACTER SET utf8 ;

-- Create users for our demo
CREATE USER 'demo1'@'localhost' IDENTIFIED BY 'password';
CREATE USER 'demo2'@'localhost' IDENTIFIED BY 'password';
CREATE USER 'demo3'@'localhost' IDENTIFIED BY 'password';
CREATE USER 'demo4'@'localhost' IDENTIFIED BY 'password';
-- Grant privileges
GRANT ALL PRIVILEGES ON BROKERS.* TO 'demo1'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON BROKERS.* TO 'demo2'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON BROKERS.* TO 'demo3'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON BROKERS.* TO 'demo4'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

-- Alter user to use MySQL Native password
-- https://github.com/mysqljs/mysql/issues/2248
ALTER USER 'demo1'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
ALTER USER 'demo2'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
ALTER USER 'demo3'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
ALTER USER 'demo4'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
FLUSH PRIVILEGES;

-- Create tables
CREATE TABLE BROKERS.BROKER_DETAILS (
  ADDRESS VARCHAR(256) NULL,
  CHECKSUM VARCHAR(64) NULL,
  DELETE_FL VARCHAR(32) NULL,
  DISABLE_FL VARCHAR(32) NULL,
  EMAIL VARCHAR(45) NULL,
  EXCHANGE_NAME VARCHAR(256) NULL,
  FACEBOOK_URL VARCHAR(256) NULL,
  FAX VARCHAR(45) NULL,
  ID INT NOT NULL DEFAULT 0,
  LINKEDIN_URL VARCHAR(256) NULL,
  NAME VARCHAR(256) NULL,
  REGISTRATION_NUM VARCHAR(16) NOT NULL,
  SOURCE VARCHAR(45) NULL,
  TELEPHONE VARCHAR(45) NULL,
  TRADE_NAME VARCHAR(45) NULL,
  TWITTER_URL VARCHAR(256) NULL,
  TYPE VARCHAR(45) NULL,
  VALIDITY VARCHAR(45) NULL,
  WEBSITE_URL VARCHAR(256) NULL,
  VALIDITY_FROM DATETIME NULL,
  VALIDITY_TO DATETIME NULL,
  PRIMARY KEY (REGISTRATION_NUM));

-- Create indexes